config/routes.rb
Rails.application.routes.draw do

  resources :products
  root 'main#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.fetch(:product, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateAnything</title>
    <%= csrf_meta_tags %>
    <script
    src="https://code.jquery.com/jquery-3.2.1.js"
    integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
    crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet">
    <link href="animate.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/color-thief/2.0.1/color-thief.min.js">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet">    <script src = "assets/color-thief.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
    <link rel="stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular-route.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body ng-app="app">

    <ng-view>
      <%= render '/nav' %>

      <%= yield %>
    </ng-view>


    </div>

    <script>
      var app = angular.module('app', []);

      app.controller('ctrl', function($scope){

      });
    </script>
  </body>
</html>

app/views/main/index.html.erb
<%= render '/nav' %>

<div class="move-down">
<div class="hot-products-container">

  <div class="hot-product parallax-scroll1">
    <img src = "https://mlsvc01-prod.s3.amazonaws.com/7e69fcc9001/376aa4ef-1ad0-481d-8865-07b6382cea9c.png">
    <div class="hot-product-overlay ">
      <h1 class="parallax-scroll"><span >Amazon Echo</span></h1>
      <h1 class="parallax-scroll"><span>The 5 star rating</span></h1>
    </div>

  </div>
  <div class="hot-product parallax-scroll2">
    <div class="hot-product-overlay ">
      <h1><span >Iphone 7</span></h1>
      <h1><span >The 5 star rating</span></h1>
    </div>
    <img src = "https://staticshop.o2.co.uk/product/images/iphone-7-plus-rose-gold_sku-header.png?cb=e55ba7b828e6e70c863cc29ad975d2ff">
  </div>
  <div class="hot-product parallax-scroll3">
    <div class="hot-product-overlay">
      <h1><span >IBM Watson</span></h1>
      <h1><span>The 5 star rating</span></h1>
    </div>
    <img src = "http://up-pc.com/wp-content/uploads/2016/03/fa825cf1-s.png">
  </div>

</div>

<div class="main-hot-container">
  <h1 class="parallax-scroll">Wale Shine Album</h1>
  <div class="underline"></div>
  <p class="parallax-scrollp">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
  <p>The 5 star rating</p>
  <button class="btn draw-border">What's All The Fuss About?</button>
  <div style="margin-top:80px;" class="underline2"></div>

  <div class="main-hot-side-img side-img">
    <img src = "http://images.genius.com/df9fa223157bf569597dc7509274af28.1000x1000x1.jpg">
  </div>

  <div class="responsive-details">
    <h1>Wale Shine Album</h1>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
    <p class="responsive-rating">The 5 star rating</p>
    <button class="responsive-view-btn">View</button>
  </div>
</div>
<div class="whats-new">
  <h1 class="whats-new-title">What's New</h1>

  <div class="whats-new-layout-container">
  <div class="whats-new-layout">
    <img src = "http://i.ebayimg.com/00/s/MTAwM1gxMDAz/z/sYYAAOSwVJhZRmwf/$_10.JPG?set_id=880000500F">
    <h1>Title</h1>
    <p> is ng industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500</p>
    <p>5 star rating</p>
  </div>
  <div class="whats-new-layout">
    <img src = "https://upload.wikimedia.org/wikipedia/en/d/dc/DVD_cover_of_the_movie_The_Keeper.jpg">
    <h1>Title</h1>
    <p> ing indrd dummy text ever since the 1500</p>
    <p>5 star rating</p>

  </div>
    <div class="whats-new-layout">
      <img src = "http://prodimage.images-bn.com/pimages/9781338099133_p0_v5_s1200x630.jpg">
      <h1>Title</h1>
      <p> ing indrd dummy text ever since the 1500</p>
      <p>5 star rating</p>

    </div>
    <div class="whats-new-layout">
      <img src = "https://www.technobuffalo.com/wp-content/uploads/2016/03/doom-cover-new.jpg">
      <h1>Title</h1>
      <p> ing indrd dummy text ever since the 1500</p>
      <p>5 star rating</p>

    </div>
  <div class="whats-new-layout">
    <img src = "http://mediad.publicbroadcasting.net/p/vpr/files/201703/Open-piano-istock-easybuy4u-20170331_0.jpg">
    <h1>Title</h1>
    <p> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500</p>
    <p>5 star rating</p>

  </div>
  <div class="whats-new-layout last">
    <img src = "https://i.ytimg.com/vi/BPu7HNfMvlw/maxresdefault.jpg">
    <h1>Title</h1>
    <p> is simplthe printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500</p>
    <p>5 star rating</p>

  </div>
  </div>

  <div class="whats-new-side-container">
    <img src = "https://www.tcu360.com/wp-content/uploads/2017/05/13-reasons-why_0.jpg">
    <h1>13 Reasons To Die</h1>
    <p>5 star rating</p>
    <p> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500</p>

  </div>
</div>
</div>

  <h1 class="top-product">Top Product</h1>


<div class="product-of-the-week">

  <h1>Vr Headset</h1>
  <p> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make</p>
  <p>5 stars</p>
  <div class="week-img-overlay">
    <h1>Title</h1>
  </div>

  <div class="product-side-week">

    <p>Top Product</p>
    <div class="week-img-container">
      <img src = "http://www.imcardboard.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/a/iac-dscvr-amaze-010.jpg">

    </div>
  </div>


</div>
<div class="two-container">
  <div style="margin-left:50px; background: rgb(220,220,250)" class="last-two-product-showcase">
      <h1>God Of War 4</h1>
    <img src = "https://s-media-cache-ak0.pinimg.com/736x/d6/d7/9e/d6d79ec84cc4edd0087c3bcb16581ad4--martin-sheen-martin-omalley.jpg">
  </div>

  <div style="background:rgb(222,184,135);" class="last-two-product-showcase">
      <h1>Mass Effect 3</h1>

    <img src = "http://www.entertainmentearth.com/images/AUTOIMAGES/PBMGH029lg.jpg">

  </div>

</div>

<div class="bottom-footer">

</div>

<script src="assets/jQuery.scrollSpeed.js"></script>

<script>


    $(window).scroll(function(){

      wScroll = $(this).scrollTop();
      console.log(wScroll);

      if(wScroll > 313){
          $(".underline").addClass("add-width")
      }
      if(wScroll > 792){
          $(".underline2").addClass("add-width")
      }

      if(wScroll< 313){
          $(".underline").removeClass("add-width")

      }
      if(wScroll < 792){
          $(".underline2").removeClass("add-width")
      }
      $(".parallax-scroll").css({
          "transform":'translate(0px, ' + wScroll/-10 + '%)'
      });
      $(".parallax-scroll1").css({
          "transform":'translate(0px, ' + wScroll/-25 + '%)'
      });
      $(".parallax-scroll2").css({
          "transform":'translate(0px, ' + wScroll/-10 + '%)'
      });
      $(".parallax-scroll3").css({
          "transform":'translate(0px, ' + wScroll/-25 + '%)'
      });
      $(".parallax-scrollp").css({
          "transform":'translate(0px, ' + wScroll/-45 + '%)'
      });


  });

  $(".week-img-overlay").hide();
  $(".week-img-one, .week-img-two").hover(function(){

      $(".week-img-one").addClass("change-dimensions");
      $(".week-img-overlay").fadeIn("slow");

  }, function(){
      $(".week-img-one").removeClass("change-dimensions");
      $(".week-img-overlay").fadeOut("slow");

  });
</script>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>